# Database Connection
spring.datasource.url=jdbc:mysql://SZT9ygtaqiFJip5.root:imUcdRmsDqum5ANY@gateway01.us-east-1.prod.aws.tidbcloud.com:4000/equipment_scheduler
spring.datasource.username=SZT9ygtaqiFJip5.root
spring.datasource.password=imUcdRmsDqum5ANY

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server Port
server.port=${PORT:8080}